### ISSUE TITLE
Illformed requirement ["< 2.1, >= 1.8"]

### ISSUE THREAD

**Issue by Ye-Yuan** [seattlerb/zentest#40]
Illformed requirement ["< 2.1, >= 1.8"]
Could not find ZenTest-4.9.1 in any of the sources

Just not sure why this happened when I trying to start rails server.

**Comment by zenspider** [comment]
Since most people have moved on to newer versions of rubygems this issue seems moot. Closing for now...but I may reopen and just leave it forever if the issue rises again.

Update your rubygems, folks! It's good for you!

**Comment by jayands** [comment]
I had this issue, too--- the simplest solution is to remove the spaces in the requirements, i.e., from `Gem::Requirement.new(["< 3.0", ">= 1.8"])` to `Gem::Requirement.new(["<3.0", ">=1.8"])`. This will enable it to work with older rubies (`1.9.3-p551`, in this case) even if you keep rubygems up-to-date.
