### ISSUE TITLE
RubyGems at 2.1.1:  ZenTest requires RubyGems version < 2.1 

### ISSUE THREAD

**Issue by jkolyer** [seattlerb/zentest#48]
This bug is back, only now it's not a bug in RubyGems.  

"gem update --system" triggers the bug within ZenTest.  

This issue has been plaguing me consistently for months now.

**Comment by kinjal20** [comment]
I already have code and i want to run that code but the below error occured how to solve it?


 gem install ZenTest -v '4.9.4'
ERROR:  Error installing ZenTest:
	ZenTest requires RubyGems version < 2.2, >= 1.8. Try 'gem update --system' to update RubyGems itself.

**Comment by zenspider** [comment]
Wow... this just doesn't go away. The ticket is rather clear. Locking.
