### ISSUE TITLE
Can't find executable autotest

### ISSUE THREAD

**Issue by rosewcs345** [seattlerb/zentest#75]
Don't know if this is ZenTest issue or respec-autotest integration issue, but on  Ubuntu 
18.04.3 LTS (Bionic Beaver), using ruby 2.6.6, sinatra 2.0.2, rspec 3.3.0, rspec-autotest 1.0.0, and ZenTest 4.12.0, all bundled with Bundler version 1.17.3, I get the following error when issuing the command `bundle exec autotest`:  /usr/share/rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable autotest for gem ZenTest (Gem::Exception)
Any ideas?

**Comment by zenspider** [comment]
`autotest` and `rspec-autotest` have literally _nothing_ to do with each other and 4.12.0 of `zentest` didn't ship with `autotest` (it moved to the `minitest-autotest` gem).

So... I would suspect `rvm` is at fault here for.. _some_ reason. Try removing whatever file it is pointing at and regenerating the stubs or whatever they call it.

**Comment by zenspider** [comment]
no response in over a year. closing.
